# Generated by Django 4.1.7 on 2023-05-23 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tamanho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamanho', models.CharField(help_text='Descricao Uniforme', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Uniforme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(help_text='Descricao Uniforme', max_length=50)),
                ('valor', models.IntegerField()),
                ('tamanho', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='uniforme.tamanho')),
            ],
        ),
    ]
