# Generated by Django 4.1.7 on 2023-05-24 01:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cadastro', '0003_master_foto_delete_perfil'),
        ('uniforme', '0002_remove_uniforme_tamanho'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.master')),
                ('tamanho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uniforme.tamanho')),
                ('uniforme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uniforme.uniforme')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('tamanho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uniforme.tamanho')),
                ('uniforme', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estoque', to='uniforme.uniforme')),
            ],
        ),
    ]
