# Generated by Django 4.1.7 on 2023-05-24 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniforme', '0003_solicitacao_estoque'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacao',
            name='tamanho',
        ),
        migrations.RemoveField(
            model_name='solicitacao',
            name='uniforme',
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='uniformes',
            field=models.ManyToManyField(to='uniforme.uniforme'),
        ),
    ]
