# Generated by Django 4.1.7 on 2023-05-24 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uniforme', '0004_remove_solicitacao_tamanho_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacao',
            name='quantidade',
        ),
        migrations.RemoveField(
            model_name='solicitacao',
            name='uniformes',
        ),
        migrations.CreateModel(
            name='ItemSolicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='uniforme.solicitacao')),
                ('tamanho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uniforme.tamanho')),
                ('uniforme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uniforme.uniforme')),
            ],
        ),
    ]
