# Generated by Django 4.1.7 on 2023-05-25 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uniforme', '0005_remove_solicitacao_quantidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='uniforme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoque', to='uniforme.uniforme'),
        ),
        migrations.AlterUniqueTogether(
            name='estoque',
            unique_together={('uniforme', 'tamanho')},
        ),
    ]
