# Generated by Django 4.1.7 on 2023-06-08 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uniforme', '0006_alter_estoque_uniforme_alter_estoque_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='estoque',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='estoque',
            name='uniforme_tamanho',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='uniforme.uniforme'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='uniforme_tamanho',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='uniforme.uniforme'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uniforme',
            name='tamanho',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='uniforme.tamanho'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estoque',
            name='quantidade',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='ItemSolicitacao',
        ),
        migrations.RemoveField(
            model_name='estoque',
            name='tamanho',
        ),
        migrations.RemoveField(
            model_name='estoque',
            name='uniforme',
        ),
    ]
