# Generated by Django 4.1.7 on 2023-06-08 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uniforme', '0008_condicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoque',
            name='condicao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='uniforme.condicao'),
            preserve_default=False,
        ),
    ]
