# Generated by Django 4.1.7 on 2023-06-08 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniforme', '0010_remove_estoque_condicao_uniforme_condicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='quantidade',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
