# Generated by Django 4.1.7 on 2023-06-08 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uniforme', '0011_solicitacao_quantidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusSolicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='solicitacao',
            name='data_solicitacao',
        ),
        migrations.RemoveField(
            model_name='solicitacao',
            name='quantidade',
        ),
        migrations.RemoveField(
            model_name='solicitacao',
            name='uniforme_tamanho',
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='data_ultima_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='id_solicitacao',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ItemSolicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='uniforme.solicitacao')),
                ('uniforme_tamanho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uniforme.uniforme')),
            ],
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='uniforme.statussolicitacao'),
            preserve_default=False,
        ),
    ]
