# Generated by Django 4.1.7 on 2023-06-08 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniforme', '0012_statussolicitacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacao',
            name='id',
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='id_solicitacao',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
