# Generated by Django 4.1.7 on 2023-06-09 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uniforme', '0013_remove_solicitacao_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsolicitacao',
            name='solicitacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_solicitacao', to='uniforme.solicitacao'),
        ),
    ]
