# Generated by Django 4.2.4 on 2023-09-04 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveIntegerField()),
                ('ano', models.PositiveIntegerField()),
                ('bloqueado', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-mes', '-ano'],
            },
        ),
        migrations.CreateModel(
            name='FuncionarioCalendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveIntegerField()),
                ('ano', models.PositiveIntegerField()),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.master')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.grupofolga')),
            ],
            options={
                'ordering': ['-ano', '-mes', 'grupo', 'funcionario'],
            },
        ),
        migrations.CreateModel(
            name='DiaCalendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('calendario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendario.calendario')),
            ],
            options={
                'ordering': ['data', '-calendario'],
            },
        ),
        migrations.CreateModel(
            name='Alocacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendario.calendario')),
                ('dia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendario.diacalendario')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendario.funcionariocalendario')),
                ('posto_trabalho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.postotrabalho')),
            ],
        ),
        migrations.AddConstraint(
            model_name='funcionariocalendario',
            constraint=models.UniqueConstraint(fields=('ano', 'mes', 'funcionario', 'grupo'), name='unique_calendario_funcionario'),
        ),
        migrations.AddConstraint(
            model_name='diacalendario',
            constraint=models.UniqueConstraint(fields=('calendario', 'data'), name='unique_calendario_dia'),
        ),
    ]
