# Generated by Django 4.1.7 on 2023-02-27 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_master_foto_delete_perfil'),
        ('calendario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendario',
            name='posto_de_trabalho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.postotrabalho'),
        ),
    ]
