# Generated by Django 4.2.4 on 2023-09-17 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
        ('calendario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendario',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cadastro.area'),
            preserve_default=False,
        ),
    ]
