# Generated by Django 4.2.4 on 2023-09-17 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0002_calendario_area'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendario',
            options={'ordering': ['area', '-ano', '-mes']},
        ),
    ]
