# Generated by Django 4.1.7 on 2023-06-16 03:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0003_remove_calendario_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendario',
            name='ano',
            field=models.PositiveIntegerField(default=2023),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calendario',
            name='bloqueado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='calendario',
            name='mes',
            field=models.PositiveIntegerField(default=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diacalendario',
            name='dia_util',
            field=models.BooleanField(default=True),
        ),
    ]
