# Generated by Django 4.1.7 on 2023-06-16 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0005_diacalendario_funcionario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendario',
            name='funcionario',
        ),
    ]
