# Generated by Django 4.1.7 on 2023-06-21 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0007_remove_diacalendario_dia_util_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendario',
            options={'ordering': ['-mes', '-ano']},
        ),
        migrations.AlterModelOptions(
            name='diacalendario',
            options={'ordering': ['data', '-calendario']},
        ),
        migrations.AddConstraint(
            model_name='diacalendario',
            constraint=models.UniqueConstraint(fields=('calendario', 'data'), name='unique_calendario_dia'),
        ),
    ]
