# Generated by Django 4.1.7 on 2023-06-21 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_alter_area_options_alter_grupofolga_options_and_more'),
        ('calendario', '0008_alter_calendario_options_alter_diacalendario_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuncionarioCalendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.master')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.grupofolga')),
            ],
        ),
    ]
