# Generated by Django 4.1.7 on 2023-06-21 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0009_funcionariocalendario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funcionariocalendario',
            options={'ordering': ['grupo', 'funcionario']},
        ),
        migrations.AlterField(
            model_name='alocacao',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendario.funcionariocalendario'),
        ),
    ]
