# Generated by Django 4.1.7 on 2023-06-21 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0010_alter_funcionariocalendario_options_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='funcionariocalendario',
            constraint=models.UniqueConstraint(fields=('funcionario', 'grupo'), name='unique_calendario_funcionario'),
        ),
    ]
