# Generated by Django 4.1.7 on 2023-07-06 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0013_alter_funcionariocalendario_funcionario'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionariocalendario',
            name='ano',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionariocalendario',
            name='mes',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
