# Generated by Django 4.1.7 on 2023-07-06 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0014_funcionariocalendario_ano_funcionariocalendario_mes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funcionariocalendario',
            options={'ordering': ['-ano', '-mes', 'grupo', 'funcionario']},
        ),
        migrations.RemoveConstraint(
            model_name='funcionariocalendario',
            name='unique_calendario_funcionario',
        ),
        migrations.AddConstraint(
            model_name='funcionariocalendario',
            constraint=models.UniqueConstraint(fields=('ano', 'mes', 'funcionario', 'grupo'), name='unique_calendario_funcionario'),
        ),
    ]
