# Generated by Django 4.1.7 on 2023-02-26 03:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(help_text='Area da linha', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CdLocalIntegrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoCdIntegrado', models.IntegerField(unique=True)),
                ('nome', models.CharField(help_text='CD Local Integrado', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ClassificacaoPreco',
            fields=[
                ('codigoClassificacaoPreco', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Escritorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoEscritorio', models.IntegerField(unique=True)),
                ('nomeEscritorio', models.CharField(help_text='Nome do escritorio', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeGenero', models.CharField(help_text='Nome Genero', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='GrupoFolga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupoFolga', models.CharField(help_text='Grupo de folga', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Linha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linha', models.CharField(help_text='Linha ou sessao', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='LocalTrabalho',
            fields=[
                ('codigoLocalTrabalho', models.IntegerField(primary_key=True, serialize=False)),
                ('nomeLocalTrabalho', models.CharField(help_text='Nome abreviado', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('codigoEmpregado', models.IntegerField(primary_key=True, serialize=False)),
                ('nomeJapones', models.CharField(help_text='Nome em Japones', max_length=30)),
                ('nomeRomanji', models.CharField(help_text='Nome em Romanji', max_length=30)),
                ('dataInicioUnidade', models.DateField()),
                ('dataDesligamentoUnidade', models.DateField(blank=True, null=True)),
                ('dataDAposentadoria', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('paisCidadania', models.CharField(help_text='Pais de origem', max_length=20)),
                ('salarioHR', models.IntegerField()),
                ('novaDataChegada', models.DateField(blank=True, null=True)),
                ('reentrada', models.CharField(max_length=1)),
                ('dataIngressaoFA', models.DateField(blank=True, null=True)),
                ('dataNascimento', models.DateField(blank=True, null=True)),
                ('nomeEmpresa', models.CharField(blank=True, help_text='Nome da Empresa', max_length=30, null=True)),
                ('nomeKana', models.CharField(blank=True, help_text='Nome em Kana', max_length=30, null=True)),
                ('codigoCdMurata', models.CharField(help_text='Codigo FJ', max_length=10)),
                ('empregadoFinalMes', models.CharField(blank=True, max_length=10, null=True)),
                ('categoriaGerente', models.IntegerField(blank=True, null=True)),
                ('codigoORDIA', models.IntegerField()),
                ('dataInicioTrabalhoExpedicao', models.DateField(blank=True, null=True)),
                ('codigoFuncionarioCD', models.IntegerField()),
                ('salarioBrutoHR', models.IntegerField(blank=True, null=True)),
                ('entradaCategoria', models.CharField(max_length=10)),
                ('dao', models.CharField(blank=True, max_length=10, null=True)),
                ('categoriaRecrutamento', models.CharField(max_length=20)),
                ('quantiaPaga', models.IntegerField(blank=True, null=True)),
                ('icCard', models.IntegerField()),
                ('unidadeCard', models.CharField(max_length=10)),
                ('numeroAs', models.IntegerField(blank=True, null=True)),
                ('classificacaoContrato', models.CharField(max_length=10)),
                ('dataConversao', models.DateField(blank=True, null=True)),
                ('afiliacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastro.area')),
                ('andarPreioTrabalho', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastro.linha')),
                ('cdLocalIntegrado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastro.cdlocalintegrado')),
                ('codigoClassificacaoPreco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastro.classificacaopreco')),
                ('codigoEscritorio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastro.escritorio')),
                ('codigoLocalTrabalho', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastro.localtrabalho')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastro.genero')),
            ],
        ),
        migrations.CreateModel(
            name='NomeProcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeProcesso', models.CharField(help_text='Nome processo', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('foto', models.ImageField(blank=True, default='', null=True, upload_to='cadastro/fotos')),
            ],
        ),
        migrations.CreateModel(
            name='PrecoUnitario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomePrecoUnitario', models.CharField(help_text='Preco integrado funcao', max_length=20, unique=True)),
                ('precoUnitario', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeSexo', models.CharField(help_text='Sexo do Colaborador', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.CharField(help_text='Turno de trabalho', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidade', models.CharField(help_text='Unidade Murata', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setor', models.CharField(help_text='Setor da Area', max_length=10)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastro.area')),
            ],
        ),
        migrations.CreateModel(
            name='PostoTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posto', models.CharField(max_length=20)),
                ('horasNormais', models.IntegerField()),
                ('horasExtras', models.IntegerField()),
                ('cobranca', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], default='S', max_length=1)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastro.area')),
            ],
            options={
                'ordering': ['-cobranca', 'posto'],
            },
        ),
        migrations.CreateModel(
            name='MasterApartamentos',
            fields=[
                ('numero', models.IntegerField(primary_key=True, serialize=False)),
                ('propriedadesCD', models.CharField(max_length=20)),
                ('nomeApartamento', models.CharField(max_length=30)),
                ('numeroApartamento', models.IntegerField()),
                ('r', models.IntegerField()),
                ('p', models.IntegerField()),
                ('custoServicoPublico', models.IntegerField()),
                ('dgs', models.IntegerField()),
                ('valorTransferenciaMEnsal', models.IntegerField()),
                ('taxaAdministracao', models.IntegerField()),
                ('alugelEquipamento', models.IntegerField()),
                ('valorEstacionamento', models.IntegerField()),
                ('lga', models.IntegerField()),
                ('valorAluguel', models.IntegerField()),
                ('totalArrecadado', models.IntegerField()),
                ('telefone', models.IntegerField()),
                ('cep', models.IntegerField()),
                ('endereco', models.CharField(max_length=30)),
                ('pontoOnibus', models.CharField(blank=True, max_length=10, null=True)),
                ('numeroOnibus', models.CharField(blank=True, max_length=10, null=True)),
                ('codigoEmpregado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastro.master')),
            ],
        ),
        migrations.AddField(
            model_name='master',
            name='nomeProcesso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastro.nomeprocesso'),
        ),
        migrations.AddField(
            model_name='master',
            name='precoUnitario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastro.precounitario'),
        ),
        migrations.AddField(
            model_name='master',
            name='sexo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastro.sexo'),
        ),
        migrations.AddField(
            model_name='master',
            name='turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastro.turno'),
        ),
        migrations.AddField(
            model_name='area',
            name='linha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastro.linha'),
        ),
        migrations.AddConstraint(
            model_name='postotrabalho',
            constraint=models.UniqueConstraint(fields=('area', 'posto'), name='unique_posto_combination'),
        ),
    ]
