# Generated by Django 4.1.7 on 2023-02-26 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='master',
            old_name='andarPreioTrabalho',
            new_name='andarPredioTrabalho',
        ),
    ]
