# Generated by Django 4.2.4 on 2024-01-27 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='linha',
        ),
    ]
