# Generated by Django 4.1.7 on 2023-02-26 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_rename_andarpreiotrabalho_master_andarprediotrabalho'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='foto',
            field=models.ImageField(blank=True, default='', null=True, upload_to='cadastro/fotos'),
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
