# Generated by Django 4.1.7 on 2023-06-21 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_master_foto_delete_perfil'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ['area']},
        ),
        migrations.AlterModelOptions(
            name='grupofolga',
            options={'ordering': ['grupoFolga']},
        ),
        migrations.AlterModelOptions(
            name='linha',
            options={'ordering': ['linha']},
        ),
        migrations.AlterModelOptions(
            name='nomeprocesso',
            options={'ordering': ['nomeProcesso']},
        ),
        migrations.AlterModelOptions(
            name='precounitario',
            options={'ordering': ['nomePrecoUnitario']},
        ),
    ]
