# Generated by Django 4.1.7 on 2023-06-25 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0005_pontoonibus_remove_masterapartamentos_numeroonibus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterapartamentos',
            name='pontoOnibus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cadastro.pontoonibus'),
            preserve_default=False,
        ),
    ]
