# Generated by Django 4.1.7 on 2023-06-25 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0007_remove_masterapartamentos_numero_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterapartamentos',
            name='id',
        ),
        migrations.AddField(
            model_name='masterapartamentos',
            name='numero',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
