# Generated by Django 4.2.4 on 2023-09-04 00:55

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do Space', max_length=100)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastro.area')),
            ],
            options={
                'ordering': ['area'],
            },
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do Tema', max_length=100)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='space.space')),
            ],
            options={
                'ordering': ['space', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Topico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topico', models.CharField(help_text='Nome do Tema', max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_hora_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='space.tema')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['tema', 'topico'],
            },
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', ckeditor.fields.RichTextField()),
                ('data_hora_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_hora_resposta', models.DateTimeField(default=django.utils.timezone.now)),
                ('mensagem_original', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='space.mensagem')),
                ('topico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='space.topico')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LeituraMensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lida', models.BooleanField(default=False)),
                ('mensagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='space.mensagem')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='space',
            constraint=models.UniqueConstraint(fields=('area', 'nome'), name='unique_space_combination'),
        ),
    ]
