# Generated by Django 4.1.7 on 2023-07-11 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0008_remove_masterapartamentos_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do Space', max_length=100)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastro.area')),
            ],
            options={
                'ordering': ['area'],
            },
        ),
    ]
