# Generated by Django 4.1.7 on 2023-07-12 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do Tema', max_length=100)),
            ],
            options={
                'ordering': ['space', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Topico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topico', models.CharField(help_text='Nome do Tema', max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['tema', 'topico'],
            },
        ),
        migrations.AddConstraint(
            model_name='space',
            constraint=models.UniqueConstraint(fields=('area', 'nome'), name='unique_space_combination'),
        ),
        migrations.AddField(
            model_name='topico',
            name='tema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='space.tema'),
        ),
        migrations.AddField(
            model_name='tema',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='space.space'),
        ),
    ]
