# Generated by Django 4.1.7 on 2023-07-13 03:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0002_tema_topico_space_unique_space_combination_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField()),
                ('data_hora_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('topico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='space.topico')),
            ],
        ),
    ]
