# Generated by Django 4.1.7 on 2023-07-16 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0007_leituramensagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensagem',
            name='lida',
        ),
    ]
