# Generated by Django 4.1.7 on 2023-08-03 02:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0014_mensagem_data_hora_resposta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagem',
            name='mensagem',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
